using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Flux.Data.Models;
using Flux.Services;
// Why are these "Access" comments above here next to the usings?

namespace Flux.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class BankAccountsController : ControllerBase
{
    // This is labeled as "BankController" but it looks like you're actually returning bank accounts. This is confusing. If I were
    // just looking at the controller name I would think the resource here is a Bank not a BankAccount.
    // * Refactored Class from BankController to BankAccountsController 

    // Why is the DbContext being used here? Is it strictly for simplicity or other? Was this generated by VS as a scaffolded item?
    // Otherwise, this shouldn't be used directly in a controller and should be abstracted.
    // * Removed DBContext and created a service layer. Called the service layer through Dependency Injection.

    // As the controller currently is, what issues can you talk through in here? Ex: What should you be using instead of the DbContext and why?
    // * Created a Service Layer to seperate the logic and elemenenate code smells.

    // Have you considered authentication/authorization?

    // Is this API RESTful? Why or why not?
    // * Added Response Codes for HTTP Protocols.
    private readonly IBankAccountService _service;

  public BankAccountsController(IBankAccountService service)
    {
        _service = service;
    }

    // Are comments like this "READ ALL" necessary?
    // * Removed Unecessary comments

    [HttpGet]
    public async Task<ActionResult<IEnumerable<BankAccount>>> GetAccounts() => 
        Ok(await _service.GetAllAccountsAsync());

    [HttpGet("{id}")]
    public async Task<ActionResult<BankAccount>> GetAccount(Guid id)
    {
        var account = await _service.GetAccountByIdAsync(id);
        return account == null ? NotFound() : Ok(account);
    }

    [HttpPost]
    public async Task<ActionResult<BankAccount>> PostAccount(BankAccount account)
    {
        var createdAccount = await _service.CreateAccountAsync(account);

        return CreatedAtAction(nameof(GetAccount), new { id = createdAccount.Id }, createdAccount);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> PutAccount(Guid id, BankAccount account)
    {
        if (id != account.Id) 
        {
            return BadRequest("Mismatched Account ID");
        }

        var success = await _service.UpdateAccountAsync(id, account);
        
        if (!success) 
        {
            return NotFound();
        }

        return NoContent(); 
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteAccount(Guid id)
    {
        var success = await _service.DeleteAccountAsync(id);
        
        if (!success) 
        {
            return NotFound();
        }

        return NoContent(); 
    }
}