using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Flux.Data;        // Access the DbContext
using Flux.Data.Models; // Access the BankAccount model
// Why are these "Access" comments above here next to the usings?

namespace Flux.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class BankAccountsController : ControllerBase
{
    // This is labeled as "BankController" but it looks like you're actually returning bank accounts. This is confusing. If I were
    // just looking at the controller name I would think the resource here is a Bank not a BankAccount.
    // * Refactored Class from BankController to BankAccountsController 

    // Why is the DbContext being used here? Is it strictly for simplicity or other? Was this generated by VS as a scaffolded item?
    // Otherwise, this shouldn't be used directly in a controller and should be abstracted.

    // As the controller currently is, what issues can you talk through in here? Ex: What should you be using instead of the DbContext and why?

    // Have you considered authentication/authorization?

    // Is this API RESTful? Why or why not?
    private readonly BankDbContext _context;

    public BankAccountsController(BankDbContext context)
    {
        _context = context;
    }

    // Are comments like this "READ ALL" necessary?
    // * Removed Unecessary comments

    [HttpGet]
    public async Task<ActionResult<IEnumerable<BankAccount>>> GetAccounts()
    {
        return await _context.Accounts.ToListAsync();
    }

    [HttpGet("{id}")]
    public async Task<ActionResult<BankAccount>> GetAccount(Guid id)
    {
        var account = await _context.Accounts.FindAsync(id);
        if (account == null) return NotFound();
        return account;
    }

    [HttpPost]
    public async Task<ActionResult<BankAccount>> PostAccount(BankAccount account)
    {
        _context.Accounts.Add(account);
        await _context.SaveChangesAsync();
        return CreatedAtAction(nameof(GetAccount), new { id = account.Id }, account);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> PutAccount(Guid id, BankAccount account)
    {
        if (id != account.Id) return BadRequest();

        _context.Entry(account).State = EntityState.Modified;
        await _context.SaveChangesAsync();
        return NoContent();
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteAccount(Guid id)
    {
        var account = await _context.Accounts.FindAsync(id);
        if (account == null) return NotFound();

        _context.Accounts.Remove(account);
        await _context.SaveChangesAsync();
        return NoContent();
    }
}