[supervisord]
nodaemon=true

[program:flux-api]
command=dotnet /app/Flux.Api.dll
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/flux-api.err.log
stdout_logfile=/var/log/flux-api.out.log

[program:flux-auth]
command=dotnet /app/auth/Flux.Auth.Api.dll
directory=/app/auth
environment=ASPNETCORE_URLS="http://+:5001"
autostart=true
autorestart=true
stderr_logfile=/var/log/flux-auth.err.log
stdout_logfile=/var/log/flux-auth.out.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
